package com.tw.core.bean;

// Generated 2015-7-15 23:47:27 by Hibernate Tools 3.4.0.CR1

import com.google.gson.annotations.Expose;

import javax.persistence.OneToMany;
import java.util.HashSet;
import java.util.Set;

/**
 * Course generated by hbm2java
 */
//@Where(clause = "state!='active'")
public class Course implements java.io.Serializable {

	@Expose
	private String courseId;
	@Expose
	private String name;
	@Expose
	private String introduction;
	@Expose
	private String state;
	@Expose
	private String type;
	@OneToMany
	private Set<Schema> schemas = new HashSet<Schema>(0);

	public Course() {
	}

	public Course(String courseId) {
		this.courseId = courseId;
	}

	public Course(String courseId, String name, String introduction,
			String state, String type) {
		this.courseId = courseId;
		this.name = name;
		this.introduction = introduction;
		this.state = state;
		this.type = type;
	}

	public String getCourseId() {
		return this.courseId;
	}

	public void setCourseId(String courseId) {
		this.courseId = courseId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getIntroduction() {
		return this.introduction;
	}

	public void setIntroduction(String introduction) {
		this.introduction = introduction;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public Set<Schema> getSchemas() {
		return this.schemas;
	}

	public void setSchemas(Set<Schema> schemas) {
		this.schemas = schemas;
	}

	@Override
	public String toString() {
		return "Course{" +
				"courseId='" + courseId + '\'' +
				", name='" + name + '\'' +
				", introduction='" + introduction + '\'' +
				", state='" + state + '\'' +
				", type='" + type + '\'' +
				'}';
	}
}
