package com.tw.core.bean;

// Generated 2015-7-15 23:47:27 by Hibernate Tools 3.4.0.CR1

import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import java.util.HashSet;
import java.util.Set;

/**
 * Employee generated by hbm2java
 */
public class Employee implements java.io.Serializable {

	private String emloyeeId;
	private String gender;
	private String email;
	private String introduction;
	private String state;
	private String type;
	private String employeeName;
	private Set<Schema> schemas = new HashSet<Schema>(0);
	private Set<User> users = new HashSet<User>(0);

	public Employee() {
	}

	public Employee(String emloyeeId) {
		this.emloyeeId = emloyeeId;
	}

	public Employee(String emloyeeId, String gender, String email,
			String introduction, String state, String type,
			String employeeName, Set<Schema> schemas, Set<User> users) {
		this.emloyeeId = emloyeeId;
		this.gender = gender;
		this.email = email;
		this.introduction = introduction;
		this.state = state;
		this.type = type;
		this.employeeName = employeeName;
		this.schemas = schemas;
		this.users = users;
	}


	public String getEmloyeeId() {
		return this.emloyeeId;
	}

	public void setEmloyeeId(String emloyeeId) {
		this.emloyeeId = emloyeeId;
	}

	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getIntroduction() {
		return this.introduction;
	}

	public void setIntroduction(String introduction) {
		this.introduction = introduction;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getEmployeeName() {
		return this.employeeName;
	}

	public void setEmployeeName(String employeeName) {
		this.employeeName = employeeName;
	}

	public Set<Schema> getSchemas() {
		return this.schemas;
	}

	public void setSchemas(Set<Schema> schemas) {
		this.schemas = schemas;
	}

	public Set<User> getUsers() {
		return this.users;
	}

	public void setUsers(Set<User> users) {
		this.users = users;
	}

}
