package com.tw.core.bean;

// Generated 2015-7-15 23:47:27 by Hibernate Tools 3.4.0.CR1

import com.google.gson.annotations.Expose;

import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

/**
 * Employee generated by hbm2java
 */
@Entity
@Table(name = "employee")
public class Employee implements java.io.Serializable {

	@Expose
	private String emloyeeId;
	@Expose
	private String gender;
	@Expose
	private String email;
	@Expose
	private String introduction;
	@Expose
	private String state;
	@Expose
	private String type;
	@Expose
	private String employeeName;

	private Set<Schema> schemas = new HashSet<Schema>(0);

	private Set<User> users = new HashSet<User>(0);

	public Employee() {
	}

	public Employee(String emloyeeId) {
		this.emloyeeId = emloyeeId;
	}

	public Employee(String emloyeeId, String gender, String email,
			String introduction, String state, String type,
			String employeeName) {
		this.emloyeeId = emloyeeId;
		this.gender = gender;
		this.email = email;
		this.introduction = introduction;
		this.state = state;
		this.type = type;
		this.employeeName = employeeName;
	}


	@Id
	@Column(name = "emloyeeId")
	public String getEmloyeeId() {
		return this.emloyeeId;
	}

	public void setEmloyeeId(String emloyeeId) {
		this.emloyeeId = emloyeeId;
	}
	@Column(name = "gender")
	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}
	@Column(name = "email")
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}
	@Column(name = "introduction")
	public String getIntroduction() {
		return this.introduction;
	}

	public void setIntroduction(String introduction) {
		this.introduction = introduction;
	}
	@Column(name = "state")
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}
	@Column(name = "type")
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}
	@Column(name = "employeeName")
	public String getEmployeeName() {
		return this.employeeName;
	}

	public void setEmployeeName(String employeeName) {
		this.employeeName = employeeName;
	}
	@OneToMany
	public Set<Schema> getSchemas() {
		return this.schemas;
	}

	public void setSchemas(Set<Schema> schemas) {
		this.schemas = schemas;
	}
	@OneToMany
	public Set<User> getUsers() {
		return this.users;
	}

	public void setUsers(Set<User> users) {
		this.users = users;
	}

	@Override
	public String toString() {
		return "Employee{" +
				"emloyeeId='" + emloyeeId + '\'' +
				", gender='" + gender + '\'' +
				", email='" + email + '\'' +
				", introduction='" + introduction + '\'' +
				", state='" + state + '\'' +
				", type='" + type + '\'' +
				", employeeName='" + getEmployeeName() + '\'' +
				'}';
	}
}
