package com.tw.core.bean;

// Generated 2015-7-15 23:47:27 by Hibernate Tools 3.4.0.CR1

import javax.persistence.*;
import java.util.Date;

/**
 * Schema generated by hbm2java
 */
public class Schema implements java.io.Serializable {

	private String schemaId;
	private Course course;
	private Customer customer;
	private Employee employee;
	private Date date;
	private String state;
	private String type;

	public Schema() {
	}

	public Schema(String schemaId) {
		this.schemaId = schemaId;
	}

	public Schema(String schemaId, Course course, Customer customer,
			Employee employee, Date date, String state, String type) {
		this.schemaId = schemaId;
		this.course = course;
		this.customer = customer;
		this.employee = employee;
		this.date = date;
		this.state = state;
		this.type = type;
	}
	@Column(name = "schemaId",length = 40)
	public String getSchemaId() {
		return this.schemaId;
	}

	public void setSchemaId(String schemaId) {
		this.schemaId = schemaId;
	}

	public Course getCourse() {
		return this.course;
	}

	public void setCourse(Course course) {
		this.course = course;
	}

	@OneToMany(fetch = FetchType.LAZY,mappedBy = "customer")
	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	@Temporal(TemporalType.TIMESTAMP)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

}
