package com.tw.core.bean;

// Generated 2015-7-15 23:47:27 by Hibernate Tools 3.4.0.CR1

import com.google.gson.annotations.Expose;

import javax.persistence.*;
import java.util.Date;

/**
 * Schema generated by hbm2java
 */
@Entity
@Table(name = "schemaTable")
public class Schema implements java.io.Serializable {
@Expose
	private String schemaId;
	@Expose
	private Course course;
	@Expose
	private Customer customer;
	@Expose
	private Employee employee;
	@Expose
	private Date date;
	@Expose
	private String state;
	@Expose
	private String type;

	public Schema() {
	}

	public Schema(String schemaId) {
		this.schemaId = schemaId;
	}

	public Schema(String schemaId, Course course, Customer customer,
			Employee employee, Date date, String state, String type) {
		this.schemaId = schemaId;
		this.course = course;
		this.customer = customer;
		this.employee = employee;
		this.date = date;
		this.state = state;
		this.type = type;
	}
	@Id
	@Column(name = "schemaId")
	public String getSchemaId() {
		return this.schemaId;
	}

	public void setSchemaId(String schemaId) {
		this.schemaId = schemaId;
	}
	@ManyToOne
	@JoinColumn(name = "courseId")
	public Course getCourse() {
		return this.course;
	}

	public void setCourse(Course course) {
		this.course = course;
	}

	@ManyToOne
	@JoinColumn(name = "customerId")
	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}
	@ManyToOne
	@JoinColumn(name = "emloyeeId")
	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	//@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date")
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}
	@Column(name = "state")
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}
	@Column(name = "type")
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

}
