package com.tw.core.bean;

// Generated 2015-7-15 23:47:27 by Hibernate Tools 3.4.0.CR1

import com.google.gson.annotations.Expose;
import org.springframework.beans.factory.annotation.Autowired;

import javax.persistence.*;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name="user")
public class User implements java.io.Serializable {
	@Expose
	private String userId;
	@Expose
	private Employee employee;
	@Expose
	private String userName;
	@Expose
	private String password;
	@Expose
	private String state;
	@Expose
	private String type;

	public User() {
	}

	public User(String userId, Employee employee) {
		this.userId = userId;
		this.employee = employee;
	}

	public User(String userId, Employee employee, String userName,
			String password, String state, String type) {
		this.userId = userId;
		this.employee = employee;
		this.userName = userName;
		this.password = password;
		this.state = state;
		this.type = type;
	}
	@Id
	@Column(name="userId")
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@ManyToOne
	@JoinColumn(name = "emloyeeId")
	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}
	@Column(name="userName")
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}
	@Column(name="password")
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}
	@Column(name="state")
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}
	@Column(name="type")
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Override
	public String toString() {
		return "User{" +
				"userId='" + userId + '\'' +
				", userName='" + userName + '\'' +
				", password='" + password + '\'' +
				", state='" + state + '\'' +
				", type='" + type + '\'' +
				'}';
	}
}
