package com.tw.core.bean;

// Generated 2015-7-15 23:47:27 by Hibernate Tools 3.4.0.CR1

import org.springframework.beans.factory.annotation.Autowired;

import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;

/**
 * User generated by hbm2java
 */

public class User implements java.io.Serializable {

	private String userId;

	//	@Autowired
	@OneToOne(fetch = FetchType.LAZY)
	@JoinColumn(referencedColumnName = "employeeId")
	private Employee employee;
	private String userName;
	private String password;
	private String state;
	private String type;

	public User() {
	}

	public User(String userId, Employee employee) {
		this.userId = userId;
		this.employee = employee;
	}

	public User(String userId, Employee employee, String userName,
			String password, String state, String type) {
		this.userId = userId;
		this.employee = employee;
		this.userName = userName;
		this.password = password;
		this.state = state;
		this.type = type;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}


	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

}
